### ISSUE TITLE
Some coordinate return null when it should return results

### ISSUE THREAD

**Issue by pencilcheck** [rapomon/geojson-places#1]
40.7756929,-73.9452068

**Comment by rapomon** [comment]
> 40.7756929,-73.9452068

Hi.

This library uses the [Admin 1 – States, Provinces](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/) from Natural Earth Data, with all state polygons in GeoJSON format. Polygons are not precise and not as accurate as we would like. 

In this particular case, you can see the problem here, the blue polygon represents the GeoJSON used to get the info, and the coordinates are outside the polygon:

<img width="842" alt="map" src="https://user-images.githubusercontent.com/5431095/189658918-cd809e48-f4c4-42f5-9411-97176f1012c7.png">

Feel free to do a PR with more precise polygons.

Best regards.
